### ISSUE TITLE
stevedore generates code with unnecessary subshells

### ISSUE THREAD

**Issue by charles-dyfis-net** [pallet/stevedore#25]
Consider the following code, taken from stevedore's test suite:

``` sh
    if ! ( [ -e file1 ] ); then echo foo;fi
```

This is unnecessarily slow to execute, as the parenthesis trigger a fork operation. This use of subshells for grouping can also cause intentional side effects towards the shell's state to be thrown away.

Consider instead the following:

``` sh
    if ! { [ -e file1 ]; }; then echo foo;fi
```

**Comment by hugoduncan** [comment]
In the `bash` expression:

``` sh
if ! ( [ -e file1 ] ); then echo foo;fi
```

the parentheses do not create a sub-shell.

**Comment by charles-dyfis-net** [comment]
The creation of a subshell is trivially demonstrated using strace:

```
$ strace -f -e clone bash -c 'if ! ( [ -e file1 ] ); then echo foo; fi'
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fd322934a10) = 13104
--- SIGCHLD (Child exited) @ 0 (0) ---
foo
$ strace -f -e clone bash -c 'if ! { [ -e file1 ]; }; then echo foo; fi'
foo
```
