### ISSUE TITLE
Create commands for IO Redirection

### ISSUE THREAD

**Issue by frenchy64** [pallet/stevedore#4]
Bash has plenty of IO redirection commands like < and <&-.

These could possibly be mapped to commands as such:

``` clojure
(redir :stdout
  (~java :classpath [@CLOJURE_JARS @VIMCLOJURE_JAR]
     :server true
     :main-class vimclojure.nailgun.NGServer
     :args @port))

```

A comparison to Windows IO redirection commands should also be made to try and create a set of stevedore scripts for both OS's.

**Comment by frenchy64** [comment]
Here is a proposed solution.

``` clojure

(with-script-context [:default]
  (script
    (~with-redir [[:err :out]
                  [:out "file.txt" :append true]
                  [:err "err.txt"]
                  [[:out :err] "/dev/null"]]
      (echo "asfd")
      (echo "asfd")
      (echo "asfd"))))
```

=>

``` sh
{
 echo "asdf"
 echo "asdf"
 echo "asdf"
} 1>&2 >>file.txt 2>err.txt &>/dev/null
```

**Comment by icylisper** [comment]
How do pipes work ?  echo "asdf" | something . with-redir can take a :pipe keyword

**Comment by frenchy64** [comment]
Pipes are already in stevedore.

``` clojure
(with-script-context [:default]
  (script
    (pipe (echo "asfd")
          (grep "a")
          (echo))))
```

=>

``` sh
echo asfd | grep a | echo
```

Does it make sense to keep the distinction between pipes and IO redirection?

**Comment by icylisper** [comment]
Makes sense. with-redir is quite an useful macro to have

**Comment by hugoduncan** [comment]
I would name it with-redirect
