### ISSUE TITLE
Devise set of OS keyword descriptors

### ISSUE THREAD

**Issue by frenchy64** [pallet/stevedore#7]

**Comment by hugoduncan** [comment]
Pallet uses :centos :debian :amzn-linux :rhel :fedora :ubuntu :windows

The jclouds OsFamily enum has the following values:
AIX, ARCH, CENTOS, DARWIN, DEBIAN, ESX, FEDORA, FREEBSD, GENTOO, HPUX, LINUX,
AMZN_LINUX, MANDRIVA, NETBSD,
OEL, OPENBSD, RHEL, SIGAR, SOLARIS, SUSE, TURBOLINUX, UBUNTU, WINDOWS
